import { promises as fs } from "fs";
import path from "path";

const ROOT = process.cwd();
const MIGRATIONS_DIRS = [
  "prisma/migrations",
  "prisma/migrations_legacy_20260114_005337",
];
const OUTPUT = "docs/MIGRATION_RISK_REGISTER.md";

const HIGH = [
  /DROP\s+TABLE/i,
  /DROP\s+COLUMN/i,
  /TRUNCATE/i,
  /DELETE\s+FROM\s+\w+(?![\s\S]*WHERE)/i,
  /UPDATE\s+\w+(?![\s\S]*WHERE)/i,
  /ALTER\s+COLUMN\s+TYPE/i,
  /LOCK\s+TABLES/i,
];

const MED = [
  /ALTER\s+TABLE/i,
  /ADD\s+COLUMN/i,
  /ADD\s+CONSTRAINT/i,
  /CREATE\s+INDEX/i,
  /CREATE\s+UNIQUE\s+INDEX/i,
];

const LOW = [
  /CREATE\s+TABLE/i,
  /COMMENT/i,
];

function riskFor(sql) {
  if (HIGH.some((re) => re.test(sql))) return "HIGH";
  if (MED.some((re) => re.test(sql))) return "MED";
  if (LOW.some((re) => re.test(sql))) return "LOW";
  return "LOW";
}

function summarize(sql) {
  const ops = [];
  if (/CREATE\s+TABLE/i.test(sql)) ops.push("CREATE TABLE");
  if (/ALTER\s+TABLE/i.test(sql)) ops.push("ALTER TABLE");
  if (/CREATE\s+INDEX/i.test(sql)) ops.push("CREATE INDEX");
  if (/DROP\s+TABLE/i.test(sql)) ops.push("DROP TABLE");
  if (/DROP\s+COLUMN/i.test(sql)) ops.push("DROP COLUMN");
  if (/UPDATE\s+\w+/i.test(sql)) ops.push("UPDATE");
  if (/DELETE\s+FROM/i.test(sql)) ops.push("DELETE");
  if (ops.length === 0) return "NO-OP/OTHER";
  return ops.join(", ");
}

async function listMigrationFiles(dir) {
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    const files = [];
    for (const e of entries) {
      if (!e.isDirectory()) continue;
      const f = path.join(dir, e.name, "migration.sql");
      try {
        await fs.access(f);
        files.push({ name: e.name, file: f });
      } catch {
        // ignore
      }
    }
    return files;
  } catch {
    return [];
  }
}

function createdAtFromFolder(name) {
  const m = name.match(/^(\d{14})_/);
  if (!m) return name;
  const ts = m[1];
  return `${ts.slice(0, 4)}-${ts.slice(4, 6)}-${ts.slice(6, 8)} ${ts.slice(8, 10)}:${ts.slice(10, 12)}:${ts.slice(12, 14)}`;
}

async function main() {
  const rows = [];

  for (const base of MIGRATIONS_DIRS) {
    const full = path.join(ROOT, base);
    const list = await listMigrationFiles(full);
    for (const m of list) {
      const sql = await fs.readFile(m.file, "utf8");
      rows.push({
        migration: path.join(base, m.name),
        created_at: createdAtFromFolder(m.name),
        summary: summarize(sql),
        risk: riskFor(sql),
        notes: "",
      });
    }
  }

  if (rows.length === 0) {
    const content = `# Migration Risk Register

> Generated by scripts/migration-audit.mjs. Do not edit by hand.

| migration | created_at | summary | risk | notes |
|---|---|---|---|---|
| (no migrations found) | - | - | - | - |
`;
    await fs.writeFile(path.join(ROOT, OUTPUT), content, "utf8");
    process.exit(0);
  }

  rows.sort((a, b) => a.migration.localeCompare(b.migration));

  const lines = [
    "# Migration Risk Register",
    "",
    "> Generated by scripts/migration-audit.mjs. Do not edit by hand.",
    "",
    "| migration | created_at | summary | risk | notes |",
    "|---|---|---|---|---|",
    ...rows.map(
      (r) =>
        `| ${r.migration} | ${r.created_at} | ${r.summary} | ${r.risk} | ${r.notes} |`,
    ),
    "",
  ];

  await fs.writeFile(path.join(ROOT, OUTPUT), lines.join("\n"), "utf8");
}

main().catch((err) => {
  console.error(err);
  process.exit(2);
});
